spring.application.name=BankApp
spring.datasource.url=jdbc:h2:mem:e-bank
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080